name: InstructLab containers

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read

env:
    IMAGE_NAME: quay.io/tiran/instructlab-containers

jobs:
    container:
        name: "${{ matrix.suffix }} container"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - containerfile: Containerfile.gfx1100
                      suffix: rocm-gfx1100
                      free_diskspace: true
                    - containerfile: Containerfile.gfx1030
                      suffix: rocm-gfx1030
                      free_diskspace: true
                    - containerfile: Containerfile.cpu
                      suffix: cpu
                      free_diskspace: false
        steps:
            # container build needs lots of disk space. GHA has limited disk
            # space. Cleanup unnecessary packages.
            - run: df -h
              if: ${{ matrix.free_diskspace }}

            - name: Clean /opt and /usr/local
              if: ${{ matrix.free_diskspace }}
              run: |
                  ls -la /opt
                  sudo rm -rf /opt/hostedtoolcache
                  ls -la /usr/local /usr/local/lib
                  sudo rm -rf /usr/local
                  df -h

            - name: Clean Debian packages
              if: ${{ matrix.free_diskspace }}
              run: |
                  sudo apt purge -y -f microsoft-edge-stable google-chrome-stable firefox azure-cli google-cloud-cli mono-complete
                  sudo apt autoremove -y
                  sudo apt autoclean -y
                  # sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head -n20

            - run: df -h
              if: ${{ matrix.free_diskspace }}

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: true

            - name: Login to Quay.io
              uses: docker/login-action@v3
              with:
                  registry: quay.io
                  username: ${{ secrets.QUAY_USERNAME }}
                  password: ${{ secrets.QUAY_ROBOT_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.IMAGE_NAME }}
                  tags: |
                      type=raw,value=${{ matrix.suffix }}

            - name: Build and export image ${{ matrix.suffix }}
              uses: docker/build-push-action@v5
              with:
                  context: instructlab/
                  file: ${{ matrix.containerfile }}
                  load: true
                  push: false

            - name: Test image
              run: |
                  echo "::group::pip list"
                  docker run --rm ${{ env.IMAGE_NAME }}:${{ matrix.suffix }} pip list
                  echo "::endgroup::"
                  docker run --rm ${{ env.IMAGE_NAME }}:${{ matrix.suffix }} ilab --version
                  docker run --rm ${{ env.IMAGE_NAME }}:${{ matrix.suffix }} python3 -c 'import torch, llama_cpp'

            - name: Push ${{ env.IMAGE_NAME }}:${{ matrix.suffix }}
              uses: docker/build-push-action@v5
              with:
                  context: instructlab/
                  file: ${{ matrix.containerfile }}
                  push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
